### ISSUE TITLE
Comment by Jannik Ibsen

### ISSUE THREAD

**Issue by JannikIbsen** [EmmaOttilie/Exercises#12]
Hey Emma.

Don't count my comment here as one of 2 feedback replies you will receive, this is merely an extra quick comment.

I noticed how you mentioned you had issues making the braches retract themselves, I thought I would share 1 possible solution using a stack function.

First we make an empty array called stack:
var stack = [];

Every time we spawn a branch we can push said branch definition to the array.

stack.push('branch definition here');

Then whenever  we want to go back  "1 step" we simply utilize pop.

branch definition here = stack.pop();

It might seem a bit confusing at first, but you can read more about it here:
http://www.i-programmer.info/programming/javascript/1674-javascript-data-structures-stacks-queues-and-deques.html

The core functionality of the stack function, is that we take the latest entry added on top of the stack, rather than the first entry (which would be a queue)

(I use it in my code this week, if you need an actual example)

**Comment by EmmaOttilie** [comment]
Thank you! I'll play around with it :)
