### ISSUE TITLE
Feedback on MiniEx4 by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [EmmaOttilie/Exercises#7]
I am surprised the other group didn't feedback on your piece since the beginning of mini ex. Guess this is something needed to be addressed. 

In relation to your sketch, the sound works for me. I really like the way you pushed yourself to think about different feedback mechanism in your concept. The other thing that I have observed on your program is the balance between control and regular temporality. As your program is structured around framecount, which means there is some kind of regularity in your work that it repeats itself in an orderly manner but, as an audience, we may not easily notice it if we don't look at your code closely. I am unsure if you have thought of this when program your work? 

At the end of your README, you mentioned about pinkness. I am interested to know more about this color fetishism, why pink? and what does it help to say in relation to feedback loop?

**Comment by EmmaOttilie** [comment]
Hi Winnie. 
I forgot you could respond in here. 

I got one feedback issue on this miniex, but Maria from my group got zero. This IS kinda annoying, so yeah maybe it should be adressed in class. 

As to the notion of the audience notices the cycle, it was actually on purpose. I like the idea of the audience having to think a little to work out what is being said. 

My pinkness is in reference to my miniex2 README where I stated that I wanted to keep pink in all my exercises, as to make a theme and sort of tell a "story" of my development in coding. :)
